update docker cloud hooks

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -4,6 +4,7 @@ printf "\n##########################"
 printf "\n##  Start Custom Build  ##"
 printf "\n##########################"
 
+echo "" > hooks/names
 VERSION="$(grep 'ARG VERSION=' Dockerfile | awk -F'=' '{ print $2 }' | tr -d '"' )"
 if [[ "$SOURCE_BRANCH" =~ ^[0-9.]+$ ]]; then
 	printf "\n[RELEASE] Build for Repo: %s" 	"$DOCKER_REPO"
@@ -16,7 +17,6 @@ printf "\n-- REPO_NAME 			: %s" 				"$REPO_NAME"
 printf "\n-- IMAGE_NAME 		: %s (%s)" 		"$IMAGE_NAME" 		"$CACHE_TAG"
 printf "\n-- UMURMUR VERSION: %s" 				"$VERSION"
 printf "\n--------------------------------\n"
-IMAGES2PUSH=""
 
 buildUmurmur(){
 	UMURMUR_VERSION="$1"
@@ -29,11 +29,10 @@ buildUmurmur(){
 	docker build --build-arg VERSION="$UMURMUR_VERSION" \
 		--build-arg SSL="$SSL" \
 		--build-arg BUILD_NUMURMON="$BUILD_NUMURMON" --build-arg BUILD_UMURMUR_MONITOR="$BUILD_UMURMUR_MONITOR" \
-		-t "$NAME" . && IMAGES2PUSH="$NAME $IMAGES2PUSH" || (printf "\nCannot build %s" "$NAME"; exit 1)
+		-t "$NAME" . && echo "$NAME" >> hooks/names || (printf "\nCannot build %s" "$NAME"; exit 1)
 }
 
 buildUmurmur "$VERSION" "openssl" "Off" "Off" "$REPO_NAME:$SOURCE_BRANCH-$VERSION"
 buildUmurmur "$VERSION" "openssl" "On" 	"Off" "$REPO_NAME:$SOURCE_BRANCH-$VERSION-numurmon"
 buildUmurmur "$VERSION" "openssl" "Off" "On" 	"$REPO_NAME:$SOURCE_BRANCH-$VERSION-monitor"
 buildUmurmur "$VERSION" "openssl" "On" 	"On" 	"$REPO_NAME:$SOURCE_BRANCH-$VERSION-full"
-echo "$IMAGES2PUSH" > hooks/names
